# Generated by Django 3.1.3 on 2021-03-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_sheduledmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
